#!/usr/bin/env bash
set -e

. $_BASHMARKS_ROOT/libexec/commons.sh

_setup

source $SDIRS
target="$(eval $(echo echo $(echo \$DIR_$1)))"
if [ -d "$target" ]; then
    cd "$target"
    exec /bin/bash
elif [ ! -n "$target" ]; then
    echo -e "\033[${RED}WARNING: '${1}' bashmark does not exist\033[00m"
else
    echo -e "\033[${RED}WARNING: '${target}' does not exist\033[00m"
fi

